In [1]:
import numpy as np

#### 액션스페이스와 액션

In [2]:
action_space = ['버튼0','버튼1']
action = np.random.choice(action_space) #Choose uniformly
action #실행할 때 마다 결과가 Uniform하게 바뀜.

'버튼0'

* `action_space`와 `action`을 기억

#### 액션에 대한 보상

In [3]:
if action == '버튼0':
  reward = 1
else: reward = 10

In [4]:
reward = 1 if action == '버튼0' else 10 #위와 같은 코드

In [5]:
#10번의 시행 관찰..
action_space = ['버튼0','버튼1']
for _ in range(10):
  action = np.random.choice(action_space)
  reward = 1 if action == '버튼0' else 10
  print(action, reward)

버튼1 10
버튼1 10
버튼0 1
버튼1 10
버튼1 10
버튼0 1
버튼1 10
버튼0 1
버튼0 1
버튼1 10


#### 관찰 : 버튼0을 누르면 1이라는 보상을 받고 버튼1을 누르면 10이라는 보상을 받는 `환경(Environment)`

바람직한 학습 방향: 환경을 학습해서 어떠한 Action('버튼1')을 취할지

In [6]:
#바람직한 상황
action_space = ['버튼0','버튼1']
for _ in range(10):
  action = '버튼1'
  reward = 1 if action == '버튼0' else 10
  print(action, reward)

버튼1 10
버튼1 10
버튼1 10
버튼1 10
버튼1 10
버튼1 10
버튼1 10
버튼1 10
버튼1 10
버튼1 10


* 환경은 알 수도 있고 모를 수도 있다.

### 강화학습이란

강화학습이란 환경(Environment)를 이해하여 에이전트(Agent)가 행동(Action)을 결정하게끔 학습시키는 것.

### A: 원시코드

#### 환경을 이해하지 못한 Agent

In [7]:
action_space = [0,1]
actions = []
rewards =[]
for t in range(1,51):
  action = np.random.choice(action_space)
  reward = 1 if action == 0 else 10
  actions.append(action)
  rewards.append(reward)
  print(
      f"시도:{t}\t"
      f"행동:{action}\t"
      f"보상:{reward}\t"
      f"최근보상평균:{np.mean(rewards[-20:]):.4f}\t"
  )
  if t < 20:
    pass
  elif t == 20:
    print("---")
  else:
    if np.mean(rewards[-20:]) > 9.5:
      print('Game Clear')
      break #진짜 만에 하나의 경우가 아니라면 안됨.

시도:1	행동:1	보상:10	최근보상평균:10.0000	
시도:2	행동:0	보상:1	최근보상평균:5.5000	
시도:3	행동:0	보상:1	최근보상평균:4.0000	
시도:4	행동:1	보상:10	최근보상평균:5.5000	
시도:5	행동:1	보상:10	최근보상평균:6.4000	
시도:6	행동:0	보상:1	최근보상평균:5.5000	
시도:7	행동:0	보상:1	최근보상평균:4.8571	
시도:8	행동:0	보상:1	최근보상평균:4.3750	
시도:9	행동:0	보상:1	최근보상평균:4.0000	
시도:10	행동:0	보상:1	최근보상평균:3.7000	
시도:11	행동:0	보상:1	최근보상평균:3.4545	
시도:12	행동:0	보상:1	최근보상평균:3.2500	
시도:13	행동:0	보상:1	최근보상평균:3.0769	
시도:14	행동:0	보상:1	최근보상평균:2.9286	
시도:15	행동:0	보상:1	최근보상평균:2.8000	
시도:16	행동:0	보상:1	최근보상평균:2.6875	
시도:17	행동:0	보상:1	최근보상평균:2.5882	
시도:18	행동:0	보상:1	최근보상평균:2.5000	
시도:19	행동:1	보상:10	최근보상평균:2.8947	
시도:20	행동:0	보상:1	최근보상평균:2.8000	
---
시도:21	행동:0	보상:1	최근보상평균:2.3500	
시도:22	행동:0	보상:1	최근보상평균:2.3500	
시도:23	행동:1	보상:10	최근보상평균:2.8000	
시도:24	행동:0	보상:1	최근보상평균:2.3500	
시도:25	행동:1	보상:10	최근보상평균:2.3500	
시도:26	행동:0	보상:1	최근보상평균:2.3500	
시도:27	행동:0	보상:1	최근보상평균:2.3500	
시도:28	행동:1	보상:10	최근보상평균:2.8000	
시도:29	행동:0	보상:1	최근보상평균:2.8000	
시도:30	행동:0	보상:1	최근보상평균:2.8000	
시도:31	행동:0	보상:1	최근보상평균:2.8000	
시도:32	행동:1	보상:10	최근보상평균:3.2500	
시도:3

#### 환경을 이해한 Agent

In [8]:
action_space = [0,1]
actions = []
rewards = []

for t in range(1,51):
  action = 1
  reward = 1 if action == 0 else 10
  actions.append(action)
  rewards.append(reward)

  print(
      f'게임횟수:{t}\t'
      f'행동:{action}\t'
      f'보상:{reward}\t'
      f'최근보상평균:{np.mean(rewards[-20:]):.4f}'
  )

  if t < 20:
    pass
  elif t == 20:
    print("---")
  else :
    if np.mean(rewards[-20:]) > 9.5:
      print('Game Clear')
      break


게임횟수:1	행동:1	보상:10	최근보상평균:10.0000
게임횟수:2	행동:1	보상:10	최근보상평균:10.0000
게임횟수:3	행동:1	보상:10	최근보상평균:10.0000
게임횟수:4	행동:1	보상:10	최근보상평균:10.0000
게임횟수:5	행동:1	보상:10	최근보상평균:10.0000
게임횟수:6	행동:1	보상:10	최근보상평균:10.0000
게임횟수:7	행동:1	보상:10	최근보상평균:10.0000
게임횟수:8	행동:1	보상:10	최근보상평균:10.0000
게임횟수:9	행동:1	보상:10	최근보상평균:10.0000
게임횟수:10	행동:1	보상:10	최근보상평균:10.0000
게임횟수:11	행동:1	보상:10	최근보상평균:10.0000
게임횟수:12	행동:1	보상:10	최근보상평균:10.0000
게임횟수:13	행동:1	보상:10	최근보상평균:10.0000
게임횟수:14	행동:1	보상:10	최근보상평균:10.0000
게임횟수:15	행동:1	보상:10	최근보상평균:10.0000
게임횟수:16	행동:1	보상:10	최근보상평균:10.0000
게임횟수:17	행동:1	보상:10	최근보상평균:10.0000
게임횟수:18	행동:1	보상:10	최근보상평균:10.0000
게임횟수:19	행동:1	보상:10	최근보상평균:10.0000
게임횟수:20	행동:1	보상:10	최근보상평균:10.0000
---
게임횟수:21	행동:1	보상:10	최근보상평균:10.0000
Game Clear


### B: Env(Environment) 구현

벤디트 설명: step이라는 함수를 정의하여 agent_action을 입력받아서 액션이 0이면 1, 액션이 1이면 10의 보상을 return하는 클래스

In [27]:
class Bandit: #Action을 받으면 보상을 반환
  def step(self,agent_action):
    reward = 1 if agent_action == 0 else 10
    return reward

In [10]:
env = Bandit()

In [11]:
action = np.random.choice(action_space)env.step(action) #보상을 반환하는 함수!

1

### Bandit를 활용한 구현

#### 환경을 이해하지 못한 경우

In [15]:
action_space = [0,1]
env = Bandit()
actions = []
rewards = []

for t in range(1,51):
  action = np.random.choice(action_space)
  reward = env.step(action)
  actions.append(action)
  rewards.append(reward)

  print(
      f"차시:{t}\t"
      f"액션:{action}\t"
      f"보상:{reward}\t"
      f"최근 평균:{np.mean(rewards[-20:]):.4f}\t"
  )

  if t < 20:
    pass
  elif t == 20:
    print('---')
  else:
    if np.mean(rewards[-20:]) > 9.5:
      print('game clear')
      break

차시:1	액션:0	보상:1	최근 평균:1.0000	
차시:2	액션:0	보상:1	최근 평균:1.0000	
차시:3	액션:0	보상:1	최근 평균:1.0000	
차시:4	액션:1	보상:10	최근 평균:3.2500	
차시:5	액션:1	보상:10	최근 평균:4.6000	
차시:6	액션:0	보상:1	최근 평균:4.0000	
차시:7	액션:1	보상:10	최근 평균:4.8571	
차시:8	액션:0	보상:1	최근 평균:4.3750	
차시:9	액션:0	보상:1	최근 평균:4.0000	
차시:10	액션:0	보상:1	최근 평균:3.7000	
차시:11	액션:1	보상:10	최근 평균:4.2727	
차시:12	액션:0	보상:1	최근 평균:4.0000	
차시:13	액션:1	보상:10	최근 평균:4.4615	
차시:14	액션:1	보상:10	최근 평균:4.8571	
차시:15	액션:1	보상:10	최근 평균:5.2000	
차시:16	액션:1	보상:10	최근 평균:5.5000	
차시:17	액션:1	보상:10	최근 평균:5.7647	
차시:18	액션:0	보상:1	최근 평균:5.5000	
차시:19	액션:0	보상:1	최근 평균:5.2632	
차시:20	액션:0	보상:1	최근 평균:5.0500	
---
차시:21	액션:1	보상:10	최근 평균:5.5000	
차시:22	액션:1	보상:10	최근 평균:5.9500	
차시:23	액션:1	보상:10	최근 평균:6.4000	
차시:24	액션:0	보상:1	최근 평균:5.9500	
차시:25	액션:0	보상:1	최근 평균:5.5000	
차시:26	액션:0	보상:1	최근 평균:5.5000	
차시:27	액션:1	보상:10	최근 평균:5.5000	
차시:28	액션:0	보상:1	최근 평균:5.5000	
차시:29	액션:1	보상:10	최근 평균:5.9500	
차시:30	액션:0	보상:1	최근 평균:5.9500	
차시:31	액션:0	보상:1	최근 평균:5.5000	
차시:32	액션:0	보상:1	최근 평균:5.5000	
차시:33	액션:0	보상:1	최근 평균:5.0500	
차

### `Agent`의 구현

In [28]:
class Agent:
  def __init__(self):
    self.action_space = [0,1]
    self.action = None
    self.reward = None
    self.actions = []
    self.rewards = []
  def act(self):
    prob = [0.5,0.5]
    self.action = 1 #환경을 이해
  def save_experience(self):
    self.actions.append(self.action)
    self.rewards.append(self.reward)

### Agent의 시점별 분석

#### 시점0: init

In [37]:
env = Bandit()
agent = Agent()

In [30]:
#아무것도 저장된게 없다. 객체를 생성하면 이상태
agent.action, agent.reward,agent.actions, agent.rewards

(None, None, [], [])

#### 시점1: Agent가 action을 선택

In [38]:
agent.act()

In [32]:
agent.action, agent.reward,agent.actions, agent.rewards

(1, None, [], [])

#### 시점2: env가 agent에게 보상

In [39]:
agent.reward = env.step(agent.action) #저장을 해야지..

In [40]:
agent.action, agent.reward,agent.actions, agent.rewards

(1, 10, [], [])

#### 시점3: agent가 경험을 저장

In [41]:
agent.save_experience()

In [42]:
agent.action, agent.reward,agent.actions, agent.rewards

(1, 10, [1], [10])

### 전체 코드

In [71]:
env = Bandit()
agent = Agent()

for t in range(1,51):
  action = agent.act()
  agent.reward = env.step(action)
  agent.save_experience()
  print(
      f"시점:{t}\t"
      f"액션:{action}\t"
      f"보상:{agent.reward}\t"
      f"근래의 평균:{np.mean(agent.rewards[-20:]):.4f}"
  )

  if t < 20:
    pass
  elif t == 20:
    print('---')
  else:
    if np.mean(agent.rewards[-20:]) > 9.5:
      print('game clear')
      break

시점:1	액션:None	보상:10	근래의 평균:10.0000
시점:2	액션:None	보상:10	근래의 평균:10.0000
시점:3	액션:None	보상:10	근래의 평균:10.0000
시점:4	액션:None	보상:10	근래의 평균:10.0000
시점:5	액션:None	보상:10	근래의 평균:10.0000
시점:6	액션:None	보상:10	근래의 평균:10.0000
시점:7	액션:None	보상:10	근래의 평균:10.0000
시점:8	액션:None	보상:10	근래의 평균:10.0000
시점:9	액션:None	보상:10	근래의 평균:10.0000
시점:10	액션:None	보상:10	근래의 평균:10.0000
시점:11	액션:None	보상:10	근래의 평균:10.0000
시점:12	액션:None	보상:10	근래의 평균:10.0000
시점:13	액션:None	보상:10	근래의 평균:10.0000
시점:14	액션:None	보상:10	근래의 평균:10.0000
시점:15	액션:None	보상:10	근래의 평균:10.0000
시점:16	액션:None	보상:10	근래의 평균:10.0000
시점:17	액션:None	보상:10	근래의 평균:10.0000
시점:18	액션:None	보상:10	근래의 평균:10.0000
시점:19	액션:None	보상:10	근래의 평균:10.0000
시점:20	액션:None	보상:10	근래의 평균:10.0000
---
시점:21	액션:None	보상:10	근래의 평균:10.0000
game clear


### Agent 구현 (인공지능)

- 데이터가 스스로 데이터를 보고 학습할 수 있도록 설계하자.. by `agent.learn()`

In [49]:
agent.actions, agent.rewards

([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10])

In [72]:
actions = np.array(agent.actions)
rewards = np.array(agent.rewards)

In [73]:
actions = np.append(actions,0)
rewards = np.append(rewards,1)

In [74]:
actions

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

In [75]:
rewards

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10,  1])

In [84]:
q0 = rewards[actions == 0].mean()
q1 = rewards[actions == 1].mean()

In [85]:
q_table = np.array([q0,q1])
q_table

array([ 1., 10.])

In [87]:
q_table/q_table.sum() #보상 비

array([0.09090909, 0.90909091])

In [88]:
prob = q_table/q_table.sum() #보상 비를 확률로 지정

In [96]:
np.random.choice(action_space,size= 10, p= prob)
#확실히 1이 더 자주 나오긴 한다.

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1])

#### 최종 Agent

상황.. 위의 방식을 사용하여 Agent를 완성하라\
t < 0 일 땐 균등하게 action, t >= 20부터 q_table을 바탕으로 한 갱신된 확률로 수행

In [125]:
class Agent:
  def __init__(self):
    self.action_space = [0,1]
    self.action = None
    self.reward = None
    self.actions = []
    self.rewards = []
    self.q_table = np.array([0.001,0.001])
    self.n_experience = 0
  def act(self):
    if self.n_experience <= 20:
      self.action = np.random.choice(self.action_space) #학습 전엔 uniform
    else:
      prob = self.q_table/ self.q_table.sum()
      self.action = np.random.choice(self.action_space, p = prob) #그냥 하나 주면 알아서 첫 사건에 prob 나머지 사건에 1-prob 할당
  def save_experience(self):
    self.actions.append(self.action)
    self.rewards.append(self.reward)
    self.n_experience = self.n_experience + 1
  def learn(self):
    if self.n_experience < 20:
      pass
    else:
      actions = np.array(self.actions)
      rewards = np.array(self.rewards)
      q0,q1 = rewards[actions == 0].mean(), rewards[actions ==1].mean()
      self.q_table = np.array([q0,q1])

최종 코드

In [123]:
class Agent:
  def __init__(self):
      self.action_space = [0,1]
      self.action = None
      self.reward = None
      self.actions = []
      self.rewards = []
      self.q_table = np.array([0.001,0.001])
      self.n_experience = 0
  def act(self):
      if self.n_experience <= 20:
        self.action = np.random.choice(self.action_space)
      else:
        prob = self.q_table/ self.q_table.sum()
        self.action = np.random.choice(self.action_space,p = prob )
  def save_experience(self):
    self.actions.append(self.action)
    self.rewards.append(self.reward)
    self.n_experience = self.n_experience + 1
  def learn(self):
    if self.n_experience < 20:
        pass
    else:
        actions = np.array(self.actions)
        rewards = np.array(self.rewards)
        q0,q1 = rewards[actions==0].mean(), rewards[actions==1].mean()
        self.q_table = np.array([q0,q1])

In [128]:
env = Bandit()
agent = Agent()

for t in range(1,51):
  agent.act()
  agent.reward = env.step(agent.action)
  agent.save_experience()
  agent.learn()

  print(
      f"t:{t}\t"
      f"action:{agent.action}\t"
      f"reward:{agent.reward}\t"
      f"recent mean:{np.mean(agent.rewards[-20:])}\t"
  )

  if t < 20:
    pass
  elif t == 20:
    print('---')
  else:
    if np.mean(agent.rewards[-20:]) > 9.5:
      print('game clear')
      break

t:1	action:0	reward:1	recent mean:1.0	
t:2	action:1	reward:10	recent mean:5.5	
t:3	action:1	reward:10	recent mean:7.0	
t:4	action:0	reward:1	recent mean:5.5	
t:5	action:0	reward:1	recent mean:4.6	
t:6	action:0	reward:1	recent mean:4.0	
t:7	action:1	reward:10	recent mean:4.857142857142857	
t:8	action:0	reward:1	recent mean:4.375	
t:9	action:0	reward:1	recent mean:4.0	
t:10	action:1	reward:10	recent mean:4.6	
t:11	action:1	reward:10	recent mean:5.090909090909091	
t:12	action:0	reward:1	recent mean:4.75	
t:13	action:1	reward:10	recent mean:5.153846153846154	
t:14	action:1	reward:10	recent mean:5.5	
t:15	action:0	reward:1	recent mean:5.2	
t:16	action:0	reward:1	recent mean:4.9375	
t:17	action:1	reward:10	recent mean:5.235294117647059	
t:18	action:0	reward:1	recent mean:5.0	
t:19	action:1	reward:10	recent mean:5.2631578947368425	
t:20	action:0	reward:1	recent mean:5.05	
---
t:21	action:1	reward:10	recent mean:5.5	
t:22	action:1	reward:10	recent mean:5.5	
t:23	action:1	reward:10	recent mean: